services:
   app:
      build:
        context: .
        dockerfile: Containerfile
      container_name: express-typescript-template
      ports:
      - "${PORT:-3000}:3000"
      env_file:
        - .env
      healthcheck:
        test: ["CMD", "curl", "-fs", "http://localhost:3000/health"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
        start_interval: 5s
